### PR TITLE
Remove Cargo.lock from version control

### LINKED ISSUE #8: Remove Cargo.lock from version control
As per Cargo Book's wisdom, libraries should not have Cargo.lock checked in to version control: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

### PR DESCRIPTION
**Pull request by aurabindo**
Closes #8

Signed-off-by: Aurabindo Jayamohanan <mail@aurabindo.in>

### CODE REVIEW

**Comment by aurabindo** [comment]
Thats weird, locally the tests are all passing for me. Whats the problem ?

**Comment by joeirimpan** [comment]
@aurabindo rebuilded it.

**Comment by joeirimpan** [comment]
Can you send the PR to develop branch and close this one?

**Comment by aurabindo** [comment]
Done, please see #9 but it fails too

**Pull request closed without merging**
